/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.voight.morse.morsepractice.ui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import org.voight.morse.morsepractice.MorsePlayer;

/**
 *
 * @author Jeffrey Voight <jeff.voight@gmail.com>
 */
public class MorsePracticePad extends javax.swing.JFrame {

    private boolean immediatePlay = false;
    private MorsePlayer morsePlayer;
    private int frequency = 44100, hz = 700, gpm = 10, groups = 5;
    //practice listen testing
    private Mode mode = Mode.PRACTICE;
    private boolean playing = false;

    /**
     *
     */
    public enum Mode {

        /**
         *
         */
        PRACTICE,
        /**
         *
         */
        LISTEN,
        /**
         *
         */
        TESTING;
    }

    /**
     * Creates new form MorsePracticePad
     */
    public MorsePracticePad() throws IOException, LineUnavailableException {
        initComponents();
        enablePracticeMode();
        morsePlayer = new MorsePlayer(frequency, hz, gpm);
    }

    private void enablePracticeMode() {
        mode = Mode.PRACTICE;
        this.groupCountLabel.setVisible(false);
        this.groupLabel.setVisible(false);
        this.groupSlider.setVisible(false);
        this.immediatePlayCheckBox.setEnabled(true);
        this.letterCanvas.setVisible(true);

    }

    private void enableListenMode() {
        mode = Mode.LISTEN;
        this.groupCountLabel.setVisible(false);
        this.groupLabel.setVisible(false);
        this.groupSlider.setVisible(false);
        this.immediatePlayCheckBox.setSelected(false);
        this.immediatePlayCheckBox.setEnabled(false);
        this.letterCanvas.setVisible(true);

    }

    private void enableTestingMode() {
        mode = Mode.LISTEN;
        this.groupCountLabel.setVisible(true);
        this.groupLabel.setVisible(true);
        this.groupSlider.setVisible(true);
        this.immediatePlayCheckBox.setSelected(false);
        this.immediatePlayCheckBox.setEnabled(false);
        this.letterCanvas.setVisible(false);
    }

    private void changeMode() {
        if (this.practiceRadioButton.isSelected()) {
            enablePracticeMode();
        } else if (this.listenRadioButton.isSelected()) {
            enableListenMode();
        } else if (this.testingRadioButton.isSelected()) {
            enableTestingMode();
        } 
    }

    private void changeGroupCount() {
        groups = this.groupSlider.getValue();
        this.groupCountLabel.setText(groups + " Groups");
    }

    private void changeGPMCount() {
        gpm = this.gpmSlider.getValue();
        this.gpmCountLabel.setText(gpm + " GPM");
        restartMorsePlayer();
    }

    private void changeFrequency() {
        hz = this.frequencySlider.getValue();
        this.frequencyCountLabel.setText(hz + " Hz");
        restartMorsePlayer();
    }

    private void changeImmediatePlay() {
        immediatePlay=this.immediatePlayCheckBox.isSelected();
    }

    private void playInputText() {
        String text = this.inputTextField.getText();
    }

    private void restartMorsePlayer() {
        try {
            morsePlayer = new MorsePlayer(frequency, hz, gpm);
        } catch (IOException | LineUnavailableException ex) {
            Logger.getLogger(MorsePracticePad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeButtonGroup = new javax.swing.ButtonGroup();
        modePanel = new javax.swing.JPanel();
        practiceRadioButton = new javax.swing.JRadioButton();
        listenRadioButton = new javax.swing.JRadioButton();
        testingRadioButton = new javax.swing.JRadioButton();
        textInputPanel = new javax.swing.JPanel();
        inputTextField = new javax.swing.JTextField();
        textInputLabel = new javax.swing.JLabel();
        immediatePlayCheckBox = new javax.swing.JCheckBox();
        playButton = new javax.swing.JButton();
        controlsPanel = new javax.swing.JPanel();
        groupsPanel = new javax.swing.JPanel();
        groupLabel = new javax.swing.JLabel();
        groupCountLabel = new javax.swing.JLabel();
        groupSlider = new javax.swing.JSlider();
        gpmPanel = new javax.swing.JPanel();
        gpmLabel = new javax.swing.JLabel();
        gpmCountLabel = new javax.swing.JLabel();
        gpmSlider = new javax.swing.JSlider();
        frequencyPanel = new javax.swing.JPanel();
        frequencyLabel = new javax.swing.JLabel();
        frequencyCountLabel = new javax.swing.JLabel();
        frequencySlider = new javax.swing.JSlider();
        displayPanel = new javax.swing.JPanel();
        codeCanvas = new java.awt.Canvas();
        letterCanvas = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        modePanel.setBackground(new java.awt.Color(204, 204, 204));
        modePanel.setName("modesPanel"); // NOI18N

        modeButtonGroup.add(practiceRadioButton);
        practiceRadioButton.setSelected(true);
        practiceRadioButton.setText("Practice Mode");
        practiceRadioButton.setToolTipText("Enter text and press play to hear.");
        practiceRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                practiceRadioButtonStateChanged(evt);
            }
        });

        modeButtonGroup.add(listenRadioButton);
        listenRadioButton.setText("Listen Mode");
        listenRadioButton.setToolTipText("Listen to random Morse Code.");
        listenRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                listenRadioButtonStateChanged(evt);
            }
        });

        modeButtonGroup.add(testingRadioButton);
        testingRadioButton.setText("Testing Mode");
        testingRadioButton.setToolTipText("Play code and see how well you copied.");
        testingRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                testingRadioButtonStateChanged(evt);
            }
        });

        javax.swing.GroupLayout modePanelLayout = new javax.swing.GroupLayout(modePanel);
        modePanel.setLayout(modePanelLayout);
        modePanelLayout.setHorizontalGroup(
            modePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(practiceRadioButton))
                    .addGroup(modePanelLayout.createSequentialGroup()
                        .addGroup(modePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listenRadioButton)
                            .addComponent(testingRadioButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        modePanelLayout.setVerticalGroup(
            modePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modePanelLayout.createSequentialGroup()
                .addComponent(practiceRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listenRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(testingRadioButton)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        textInputPanel.setBackground(new java.awt.Color(204, 204, 204));

        inputTextField.setToolTipText("Enter text to be played as Morse Code");
        inputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTextFieldKeyTyped(evt);
            }
        });

        textInputLabel.setText("Text Input");

        immediatePlayCheckBox.setText("Immediate Play");
        immediatePlayCheckBox.setToolTipText("Play Morse Code as symbols are entered.");
        immediatePlayCheckBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                immediatePlayCheckBoxPropertyChange(evt);
            }
        });

        playButton.setText("Play");
        playButton.setToolTipText("Play the input text Morse Code");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout textInputPanelLayout = new javax.swing.GroupLayout(textInputPanel);
        textInputPanel.setLayout(textInputPanelLayout);
        textInputPanelLayout.setHorizontalGroup(
            textInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(textInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputTextField)
                    .addGroup(textInputPanelLayout.createSequentialGroup()
                        .addComponent(textInputLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(immediatePlayCheckBox))
                    .addGroup(textInputPanelLayout.createSequentialGroup()
                        .addComponent(playButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        textInputPanelLayout.setVerticalGroup(
            textInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(textInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textInputLabel)
                    .addComponent(immediatePlayCheckBox))
                .addGap(12, 12, 12)
                .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        controlsPanel.setBackground(new java.awt.Color(153, 255, 255));

        groupsPanel.setPreferredSize(new java.awt.Dimension(500, 75));

        groupLabel.setText("Group Count");
        groupLabel.setToolTipText("");

        groupCountLabel.setText("5 Groups");
        groupCountLabel.setToolTipText("A Group is 5 symbols");

        groupSlider.setMajorTickSpacing(5);
        groupSlider.setMaximum(25);
        groupSlider.setMinimum(1);
        groupSlider.setMinorTickSpacing(1);
        groupSlider.setPaintLabels(true);
        groupSlider.setPaintTicks(true);
        groupSlider.setSnapToTicks(true);
        groupSlider.setToolTipText("Adjusts the number of groups to test");
        groupSlider.setValue(5);
        groupSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                groupSliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout groupsPanelLayout = new javax.swing.GroupLayout(groupsPanel);
        groupsPanel.setLayout(groupsPanelLayout);
        groupsPanelLayout.setHorizontalGroup(
            groupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groupsPanelLayout.createSequentialGroup()
                .addGroup(groupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(groupSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(groupsPanelLayout.createSequentialGroup()
                        .addComponent(groupLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(groupCountLabel)))
                .addContainerGap())
        );
        groupsPanelLayout.setVerticalGroup(
            groupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupsPanelLayout.createSequentialGroup()
                .addGroup(groupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupLabel)
                    .addComponent(groupCountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        gpmPanel.setPreferredSize(new java.awt.Dimension(500, 75));

        gpmLabel.setText("Groups per Minute");
        gpmLabel.setToolTipText("");

        gpmCountLabel.setText("15 GPM");
        gpmCountLabel.setToolTipText("A Group is 5 symbols");

        gpmSlider.setMajorTickSpacing(5);
        gpmSlider.setMaximum(40);
        gpmSlider.setMinimum(5);
        gpmSlider.setMinorTickSpacing(1);
        gpmSlider.setPaintLabels(true);
        gpmSlider.setPaintTicks(true);
        gpmSlider.setSnapToTicks(true);
        gpmSlider.setToolTipText("Adjusts the speed of the Morse Code");
        gpmSlider.setValue(10);
        gpmSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                gpmSliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout gpmPanelLayout = new javax.swing.GroupLayout(gpmPanel);
        gpmPanel.setLayout(gpmPanelLayout);
        gpmPanelLayout.setHorizontalGroup(
            gpmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gpmPanelLayout.createSequentialGroup()
                .addGroup(gpmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gpmSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(gpmPanelLayout.createSequentialGroup()
                        .addComponent(gpmLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gpmCountLabel)))
                .addContainerGap())
        );
        gpmPanelLayout.setVerticalGroup(
            gpmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gpmPanelLayout.createSequentialGroup()
                .addGroup(gpmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpmLabel)
                    .addComponent(gpmCountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gpmSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        frequencyPanel.setPreferredSize(new java.awt.Dimension(500, 75));

        frequencyLabel.setText("Tone Frequency");
        frequencyLabel.setToolTipText("");

        frequencyCountLabel.setText("700 Hz");
        frequencyCountLabel.setToolTipText("Standard is 700 Hz");

        frequencySlider.setMajorTickSpacing(100);
        frequencySlider.setMaximum(1000);
        frequencySlider.setMinimum(500);
        frequencySlider.setMinorTickSpacing(50);
        frequencySlider.setPaintLabels(true);
        frequencySlider.setPaintTicks(true);
        frequencySlider.setSnapToTicks(true);
        frequencySlider.setToolTipText("Adjusts the speed of the Morse Code");
        frequencySlider.setValue(700);
        frequencySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                frequencySliderStateChanged(evt);
            }
        });
        frequencySlider.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                frequencySliderPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout frequencyPanelLayout = new javax.swing.GroupLayout(frequencyPanel);
        frequencyPanel.setLayout(frequencyPanelLayout);
        frequencyPanelLayout.setHorizontalGroup(
            frequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frequencyPanelLayout.createSequentialGroup()
                .addGroup(frequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(frequencySlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(frequencyPanelLayout.createSequentialGroup()
                        .addComponent(frequencyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(frequencyCountLabel)))
                .addContainerGap())
        );
        frequencyPanelLayout.setVerticalGroup(
            frequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frequencyPanelLayout.createSequentialGroup()
                .addGroup(frequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frequencyLabel)
                    .addComponent(frequencyCountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frequencySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout controlsPanelLayout = new javax.swing.GroupLayout(controlsPanel);
        controlsPanel.setLayout(controlsPanelLayout);
        controlsPanelLayout.setHorizontalGroup(
            controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(groupsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
            .addComponent(gpmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
            .addComponent(frequencyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
        controlsPanelLayout.setVerticalGroup(
            controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlsPanelLayout.createSequentialGroup()
                .addComponent(groupsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gpmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frequencyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        displayPanel.setBackground(new java.awt.Color(153, 153, 255));

        codeCanvas.setBackground(new java.awt.Color(255, 255, 51));

        letterCanvas.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codeCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letterCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(letterCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codeCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(controlsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(controlsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void practiceRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_practiceRadioButtonStateChanged
        changeMode();
    }//GEN-LAST:event_practiceRadioButtonStateChanged

    private void listenRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_listenRadioButtonStateChanged
        changeMode();
    }//GEN-LAST:event_listenRadioButtonStateChanged

    private void testingRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_testingRadioButtonStateChanged
        changeMode();
    }//GEN-LAST:event_testingRadioButtonStateChanged

    private void frequencySliderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_frequencySliderPropertyChange
        changeFrequency();
    }//GEN-LAST:event_frequencySliderPropertyChange

    private void immediatePlayCheckBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_immediatePlayCheckBoxPropertyChange
        changeImmediatePlay();
    }//GEN-LAST:event_immediatePlayCheckBoxPropertyChange

    private void inputTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTextFieldKeyTyped
        char keyPress = Character.toUpperCase(evt.getKeyChar());
    }//GEN-LAST:event_inputTextFieldKeyTyped

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        playInputText();
    }//GEN-LAST:event_playButtonActionPerformed

    private void groupSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_groupSliderStateChanged
        changeGroupCount();
    }//GEN-LAST:event_groupSliderStateChanged

    private void gpmSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gpmSliderStateChanged
        changeGPMCount();
    }//GEN-LAST:event_gpmSliderStateChanged

    private void frequencySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_frequencySliderStateChanged
        changeFrequency();
    }//GEN-LAST:event_frequencySliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MorsePracticePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MorsePracticePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MorsePracticePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MorsePracticePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MorsePracticePad().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MorsePracticePad.class.getName()).log(Level.SEVERE, null, ex);
                } catch (LineUnavailableException ex) {
                    Logger.getLogger(MorsePracticePad.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas codeCanvas;
    private javax.swing.JPanel controlsPanel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel frequencyCountLabel;
    private javax.swing.JLabel frequencyLabel;
    private javax.swing.JPanel frequencyPanel;
    private javax.swing.JSlider frequencySlider;
    private javax.swing.JLabel gpmCountLabel;
    private javax.swing.JLabel gpmLabel;
    private javax.swing.JPanel gpmPanel;
    private javax.swing.JSlider gpmSlider;
    private javax.swing.JLabel groupCountLabel;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JSlider groupSlider;
    private javax.swing.JPanel groupsPanel;
    private javax.swing.JCheckBox immediatePlayCheckBox;
    private javax.swing.JTextField inputTextField;
    private java.awt.Canvas letterCanvas;
    private javax.swing.JRadioButton listenRadioButton;
    private javax.swing.ButtonGroup modeButtonGroup;
    private javax.swing.JPanel modePanel;
    private javax.swing.JButton playButton;
    private javax.swing.JRadioButton practiceRadioButton;
    private javax.swing.JRadioButton testingRadioButton;
    private javax.swing.JLabel textInputLabel;
    private javax.swing.JPanel textInputPanel;
    // End of variables declaration//GEN-END:variables
}
